---
- name: Install filebeat
  apt:
    deb: "https://mirror.yandex.ru/mirrors/elastic/7/pool/main/f/filebeat/filebeat-{{ elk_version }}-amd64.deb"
    #deb: "/tmp/filebeat-{{ elk_version }}-amd64.deb"

- name: Deploy filebeat config
  template:
    src: filebeat.yml.j2
    dest: /etc/filebeat/filebeat.yml

- name: Restart filebeat
  systemd:
    name: filebeat
    enabled: true
    state: restarted