---
- name: Install zabbix repository
  apt:
    deb: https://repo.zabbix.com/zabbix/6.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.0-6+ubuntu24.04_all.deb

- name: Install zabbix-agent
  ansible.builtin.apt:
    name:
      - zabbix-agent2
      - zabbix-agent2-plugin-*
    update_cache: yes  
    state: present  

- name: Make zabbix log directory
  file:
    path: "{{ zabbix_agent_log_dir }}"
    owner: zabbix
    group: zabbix
    state: directory
    mode: '0755'

- name: Deploy zabbix agent config
  template:
    src: zabbix_agent2.conf.j2
    dest: /etc/zabbix/zabbix_agent2.conf

- name: Restart zabbix-agent2
  systemd:
    name: zabbix-agent2
    enabled: true
    state: restarted